# init_prompts.py
# INIT_PROMPTS: 50 natural, persona-aware conversation starters for LLMs

INIT_PROMPTS = [
    "As an operations manager at a mid-sized steel service center, I'm wrestling with coil-level inventory accuracy across two warehouses — what ERP features should I prioritize to avoid mis-ships and blind stock?",
    "I'm the head of sales at a metal distributor and our RFQ turnaround is killing conversion — what software patterns or ERP modules help automate quoting while preserving margin rules?",
    "We run slitting and cut-to-length work; from an operations perspective, what workflows in ERP systems actually help schedule slitting, manage mill orders, and avoid downtime?",
    "As an IT lead I need to integrate handheld barcode scanners, WMS, and ERP — what integration patterns and data models do modern steel ERPs use to keep everything synced?",
    "I'm a general manager evaluating ERP vendors — how important is industry-specific functionality (coil-level tracking, mill order management) versus heavy customization of a generic ERP?",
    "From a procurement manager's viewpoint, how can an ERP help me optimize mill order timing and supplier allocation so I don't overpay or hold excess coil inventory?",
    "As a warehouse manager, I'm curious if current ERPs have practical dispatch planning tools that coordinate trucking, staging, and delivery windows without manual spreadsheets?",
    "I lead a multi-site steel distribution business — what's the best way an ERP can give me consolidated visibility while letting each site keep local workflows?",
    "As a plant manager, I want to reduce yield loss during slitting and cutting — what ERP or MES features help measure and reduce scrap at coil level?",
    "Our CFO is pushing for faster month-end close. For a steel processor, which ERP accounting practices usually simplify allocations between mill orders, processing fees, and customer billing?",
    "I run a service center and want to support customer self-service for order tracking — how do ERPs typically expose secure order/coil visibility to customers without leaking other data?",
    "From a sales ops angle, how do modern ERPs combine CRM, order management, and pricing rules so reps can see accurate lead times when making promises to customers?",
    "I’m the quality manager — which ERP features best capture coil certifications, mill test reports, and non-conformance data so customer audits are painless?",
    "As the CEO of a small metal distributor, I want a solution that grows with us — how do I weigh a niche steel ERP against a big generic ERP when resources for customization are limited?",
    "We have complex trunking and local deliveries — what dispatch optimization features should I expect from an ERP that claims to support delivery planning for steel coils?",
    "From an operations perspective, how do ERPs model mill orders vs. service center orders, and what should I test during demos to ensure that mapping fits our workflows?",
    "I’m the head of digital transformation — how are AI features being used today to improve forecasting, dynamic pricing, and recommended inventory replenishment for metals?",
    "As a logistics manager dealing with tight delivery windows, what do ERPs offer in terms of carrier integrations, route management, and POD capture for coils and plates?",
    "I manage several steel product lines — what reporting and KPI dashboards should an ERP include so I can monitor turns, aging, and utilization by coil/lot?",
    "As a support lead, I want to know how easy it is to onboard shop floor staff — which ERPs have simpler UIs or mobile workflows for warehouse operators and slitting crews?",
    "From a purchasing perspective, how can an ERP help me enforce vendor contracts, manage supplier lead times, and avoid stockouts when mills change production schedules?",
    "I’m considering a cloud ERP for our service center — what security, backup and offline-access considerations must I check specifically for coil-handling operations?",
    "As a sales VP, how much can a steel-specific ERP reduce manual pricing errors and expedite quote-to-order cycles compared to our current Excel-driven process?",
    "I run a tubular mill; our needs are slightly different from flat roll — what ERP capabilities should I insist on for tube/pipes production tracking and inventory?",
    "As an operations analyst, can ERPs realistically track coil-level traceability from mill receipt through processing and shipping, and what design decisions make that reliable?",
    "I manage returns and rework frequently — which ERP features help track rejected coils, restocking, and customer credits without messing up inventory valuation?",
    "From a finance POV, how should ERP handle complex chargebacks: mill processing fees, slitting surcharges, and delivery charges so customer invoices match contracts?",
    "I’m the HR lead exploring 'people' and payroll modules — how well do integrated people modules work with shop-floor time capture for cost allocation in processing centers?",
    "As a prospective buyer, I want to see examples of report templates relevant to steel operations — what core reports should any demo include to prove the software fits our use cases?",
    "I run an export business — how should an ERP help with compliance documentation, country-of-origin, and export packing lists for steel shipments?",
    "We rely heavily on legacy spreadsheets — what's a realistic migration path to a steel ERP that minimizes operational disruption and keeps key historical metrics?",
    "As a maintenance manager, can ERP or allied modules help schedule preventive maintenance for slitting lines and log downtime tied to specific mill orders?",
    "I’m responsible for sustainability reporting — can ERP systems track yield, scrap, and resource usage in ways that feed ESG reports for metal operations?",
    "We're experimenting with AI-driven pricing — how do ERPs expose the right datasets for ML models so the pricing suggestions are operationally safe?",
    "As an operations director, how do I test an ERP's dispatch planning during a demo so I can be confident it handles my peak day constraints?",
    "I handle customer contracts — how do ERPs support complex contract terms like minimum order quantities, replenishment cycles, and scheduled shipments?",
    "I'm evaluating vendor support — what SLAs and onboarding packages are reasonable when moving to an industry-focused ERP for steel?",
    "As a procurement buyer I want alerts for low-turn SKUs — how good are modern ERPs at combining demand signals from orders, quotes, and forecast adjustments?",
    "I manage chain-of-custody requirements — what coil-level controls should an ERP enable so we can reconcile physical stock to system locations daily?",
    "We have complex pricing by coil weight, width, and surface finish — which ERP pricing engines let you express those rules without constant consulting?",
    "As a product manager, how do I validate an ERP's claims about 'built for steel' features during a short 2-hour vendor demo?",
    "I lead small-scale operations and need to minimize admin — which ERP features genuinely reduce daily manual reconciliation and routine admin tasks?",
    "From an operations standpoint, how does a report builder in ERP help create ad-hoc shipment or profitability reports for specific mill orders?",
    "I want to understand how ERP handles staged shipments (partial coils or split coils) — what sample workflows should I test during trial?",
    "As someone who’s used generic ERPs, what red flags should I watch for that indicate a vendor does not truly understand steel operations?",
    "I’m the CIO and care about integrations — which APIs and data export patterns should a steel ERP provide so we can plug in analytics and TMS?",
    "As a plant controller, how have other steel service centers realized ROI after implementing an industry-specific ERP — what quick wins are common?",
    "We sometimes need ad-hoc production runs — which ERP functions help schedule temporary processes while preserving traceability to the mill order?",
    "I manage a multi-brand shop floor — what user roles and permission models should an ERP support so different teams can operate safely?",
    "As procurement lead, I want to handle supplier substitutions when mills change specs — how should an ERP let me model substitutions without breaking orders?"
]
